### PR TITLE
Fix design bug in projects

### PR DESCRIPTION
**Pull request by w3bdesign**
This should fix the bug as seen below.

I also made the copyright year dynamic instead of hardcoded.

image

### CODE REVIEW

**Comment by w3bdesign** [comment]
@joan-gerard

**Comment by joan-gerard** [comment]
@w3bdesign Hi, thanks for looking into these bugs.
I am curious, what browser and/or machine were you using to recreate these design issue as I don't have this issue?

**Comment by w3bdesign** [comment]
> @w3bdesign Hi, thanks for looking into these bugs. I am curious, what browser and/or machine were you using to recreate these design issue as I don't have this issue?

@joan-gerard 

Firefox 112.0.1 with Windows 10

**Comment by w3bdesign** [comment]
Can confirm the same issue is in Chrome as well.

It seems that the issue is with the resolution, as I have a 27" monitor with 2560 x 1440 resolution.

**Pull request merged**
